name: Build Marlin Firmware

on:
  push:
    branches:
      - master
      - main

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest
    env:
      BOARD: mega2560
      MARLIN_VER: 2.0.6.1

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Compile firmware
        run: |
          docker build -t marlin-build .
          docker run \
            -u root:root \
            -e BOARD=$BOARD \
            -e USE_TAG=$MARLIN_VER \
            -v $(pwd)/firmware:/home/platformio/build \
            -v $(pwd)/config:/home/platformio/CustomConfiguration \
            marlin-build

      - uses: actions/upload-artifact@v2
        with:
          name: marlin-firmware-a20t-btt3in1
          path: firmware/
